// ******* MIDLANDER NAMES ******
var midlanderMaleFirstname = ["Ailill", "Airell", "Alan", "Albion", "Allyn", "Bedwyr", "Bardon", "Bran", "Brent", "Bryant", "Cradawg", "Cedric", "Devyn", "Donat", "Douglhas", "Doy", "Drem", "Driskell", "Edward", "Eddard", "Elidor", "Ewyn", "Fred", "Finnibar", "Floyd", "Ferghus", "Galvan", "Glen", "Guye", "Kayne", "Kevin", "Kelvin", "Neal", "Neese", "Nyle", "Reagan", "Wynne", 'John', 'Johnathon', 'Dillan', 'Dillian', 'Frank', 'Frankfort', 'Tim', 'Timothy', 'Sylvester', 'Sam', 'Gregory', 'Gergori', 'James', 'Jameson', 'Jaimes', 'Jim', 'Albert', 'Alburt', 'Albus', 'Albys', 'Brent', 'Brint', 'Brett', 'Jaochim', 'Tadd', 'Thadeus', 'Dick'];
var midlanderFemaleFirstname = ["Aife", "Alane", "Ardena", "Alys", "Aleen", "Diva", "Divone", "Devona", "Gilda", "Gwenevyr", "Gwynn", "Ginerva", "Jennifer", "Jenny", "Joyce", "Nara", "Reaghan", "Ronat", "Rowena", "Selma", "Sally", "Samantha", "Sandra", "Simone", "Winnie", "Wynnie", "Winona", "Yseult"];
var midlanderSurname = ["Baker", "Baxter", "Beddingham", "Bettington", "Maxwell", "Stone", "Johnson", "Miller", "Stark", "Brown", "Browne", "Skinner", "William", "Williams", "Williamson", "Moor", "Moore", "Morrington", "Allerton", "Addington", "Clare", "Hayes", "Hayley", "Hartford", "Huckabee", "Huxley", "Kenley", "Kent", "Darby", "Cumberbatch", "Davenport", "Dayton", "Axton", "Emsworth", "Bradshaw", "Brent", "Brownrigg", "Bristol", "Garrick", "Graham", "Middleton", "Morton", "Langston", "Lancaster", "Nash", "Nibley","Northcroft", "Greshem", "Cason", "Chester", "Carlyle", "Hale", "Hales", "Pickerton", "Pickering", "Payton", "Nye", "Norton", "Perry", "Paxton", 'Payton'];

// ******* HIGHLANDER NAMES *******
var highlanderMaleFirstname = ["Aadolf", "Aart", "Abbe", "Abelino", "Ade", "Adelmar", "Adelmo", "Adelmund", "Cade", "Cadman", "Caedmon", "Caesar", "Caetano", "Gabe", "Gabor", "Gage", "Gaidar", "Kaapo", "Kade", "Kael", "Kagan", "Paavo", "Pacifico", "Padma", "Padraig", "Page", "Pace", "Saburo", "Sage", "Sahib", "Sailor", "Salazar", "Salem", "Salomon", "Saladin", "Wade", "Wagner", "Wainwright", "Walden", "Walenty", "Walker", "tabor", "Tad", "Tadeas", "Taft"];
var highlanderFemaleFirstname = ["Aaliyah", "Abby", "Abela", "Abigail", "Abbarane", "Baako", "Bai", "Babette", "Fabiola", "Fabia", "Faith", "Fairy", "Fang", "Fan", "Hadassah", "Halina", "Haloke", "Hana", "Handan", "Kaarina", "Kahula", "Kaia", "Kainoa", "Kaipo", "Padma", "Hylda", "Hilda", "Fordola", "Palmira", "Paitha", "Paige", "Pam", "Payne", "Tadita", "Tabitha", "Tabby", "Takisha", "Talia", "Talim", "Tal", "Yadira", "Yaffa", "Yaroslava", "Yejide"];
var highlanderSurname = ["Muller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann", 'Schafer', "Wolf", "Klein", "Kruger", "Werner", "Krause", "Lehmann", "Schmid", "Schulze", "Maier","Koler", "Brood", "Blooder", "Zimmerman", "Harmann", "Franke", "Vogt", "Otto", "Seidel", "Heinrich", "Brandt", "Hass", "Beck","Roth", "Berger", "Winkler", "Keller",'Volger', "Thomas", "Pfeiffer", "Bergmann", "Horn", "Engel", "Pohl", "Zieglar", "Ziegler", "Wolff", "Gaertner","Gardner"];

// ******* SEEKER OF THE SUN NAMES *******
var seekerMaleFirstname = ["A'ba", "A'ht", "B'amu", "B'anhi", "B'atih", "B'hee", "B'hen", "C'ott", "D'ajha", "D'hol", "E'nah", "E'si", "F'alh", "F'huz", "G'ayha", "G'huh", "G'inwa", "H'alha", "H'eleh", "H'ena", "J'esal", "J'hah", "J'hida", "J'inh", "J'utah", "K'hilo", "K'huba", "K'uzh", "L'huil", "L'oha", "M'ah", "M'alha", "M'enh", "M'hasi", "M'itnu", "N'aweh", "N'eneh", "N'dai", "N'itsah", "O'dh", "O'ya", "P'ahsh", "P'etih", "P'inha", "Q'esh", "Q'olnh", "R'aha", "R'ahz", "R'hiki", "R'hof", "R'hul", "R'hun", "R'ihll", "S'hikhu", "S'tah", "T'enbe", "T'yaka", "T'yanu", "T'yata", "T'ykha", "V'huh", "Y'elho", "Z'het", "Z'ibho", "Z'ula"];
var seekerFemaleFirstname = ["A'bodji", "A'debh", "A'hnebb", "A'labali", "A'mneko", "A'rhll", "A'rimbeh", "A'shaht", "B'aharra", "B'andala", "B'honja", "B'howaka", "B'howaqi", "B'okhn", "B'olaff", "B'olata", "B'rohka", "B'ulea", "C'anago", "C'idjaa", "D'anafa", "D'asshym", "D'atnan", "D'elika", "D'hakya", "D'hamya", "D'hilogo", "D'hinek", "D'hodjbi", "D'hovaka", "D'oyagha", "D'jawana", "D'jongo", "D'oyagha", "D'yalani", "D'yunbu", "E'baloh", "F'hiroh", "F'udzol", "G'honako", "G'nayak", "G'oromuli", "H'ahtoa", "H'obhas", "H'ozqha", "H'ynho", "I'ntana", "J'himei", "J'ughal", "J'uramm", "J'usana", "K'ahmuli", "K'ahzuna", "K'alkaya", "K'ebbe", "K'hebica", "K'henna", "K'holbeh", "K'honebb", "K'oliwe", "K'onbalha", "K'onelua", "K'onnala", "K'ontai", "K'orolon", "'Lafumyn", "'Lahmui", "L'ahono", "L'aiboli", "L'akshai", "L'amahni", "L'eytai", "L'haminn", "L'inbho", "L'layan", "L'loon", "L'looni", "L'olamo", "L'oonh", "L'yhhia", "L'yhia", "M'ajha", "M'allibo", "M'allpa", "M'aritaa", "M'ellpa", "M'halawi", "M'helgo", "M'hitra", "M'ibhas", "M'ihgazoo", "M'okkri", "M'oldva", "M'olminn", "M'ollpa", "M'olosi", "M'yhoi", "N'aago", "N'aanza", "N'abyano", "N'agali", "N'aidjaa", "N'airoh", "N'anghal", "N'angho", "N'apa", "N'apha", "N'asshym", "N'bulea", "N'danya", "N'dolobo", "N'domii", "N'halki", "N'hapla", "N'ibnpha", "N'imuili", "N'mulika", "N'oggya", "N'olosi", "N'ophlo", "O'byano", "O'lhmyn", "O'ndolo", "O'nggo", "O'ngho", "P'aghlo", "P'ahtalo", "P'ayan", "P'erjha", "P'iqoi", "P'ondhao", "P'tolmi", "Q'awhau", "R'aemha", "R'ahtalo", "R'alka", "R'anmaia", "R'habye", "R'hanbolo", "R'hoyod", "R'hunlika", "S'eptha", "S'hakkal", "S'htola", "S'huwahe", "S'onjha", "S'sapa", "S'umbla", "S'ushmo", "T'adhara", "T'ahjha", "T'ajha", "T'alhdi", "T'andhaa", "T'anmo", "T'chakha", "T'elihgo", "T'olwann", "T'owali", "W'abati", "W'ahaii", "W'ahnako", "W'onjhali", "Y'alwann", "Y'andih", "Y'antaa", "Z'alikko", "Z'amqo", "Z'anza", "Z'azanh", "Z'entsa", "Z'humii", "Z'imzizi", "Z'uhjha", "Z'umyn"];
var seekerMaleSurname = ["Tia", "Nunh"];
var seekerFemaleSurname = ["Aba", "Aht", "Bamu", "Banhi", "Batih", "Bhee", "Bhen", "Cott", "Dajha", "Dhol", "Enah", "Esi", "Falh", "Fhuz", "Gayha", "Ghuh", "Ginwa", "Halha", "Heleh", "Hena", "Jesal", "Jhah", "Jhida", "Jinh", "Jutah", "Khilo", "Khuba", "Kuzh", "Lhuil", "Loha", "Mah", "Malha", "Menh", "Mhasi", "Mitnu", "Naweh", "Neneh", "Ndai", "Nitsah", "Odh", "Oya", "Pahsh", "Petih", "Pinha", "Qesh", "Qolnh", "Raha", "Rahz", "Rhiki", "Rhof", "Rhul", "Rhun", "Rihll", "Shikhu", "Stah", "Tenbe", "Tyaka", "Tyanu", "Tyata", "Tykha", "Vhuh", "Yelho", "Zhet", "Zibho", "Zula"];

// ******** KEEPER OF THE MOON NAMES *******
var keeperMaleFirstname = ["Amh", "Bathu", "Bathus", "Daca", "Detoh",  "Doyoh", "Fihpo", "Giah", "Gota", "Hahs", "Hawu", "Hnaba", "Khuja", "Khuma", "Kiht", "Koh", "Mauh", "Mhih", "Mikh", "Monh", "Muijh", "Naih", "Naoh", "Nashu", "Nemoh", "Ngha", "Nhago", "Nheu", "Nozih", "Oah", "Oghii", "Okhi", "Okkh", "Pawah", "Pelhi", "Pimoh", "Poki", "Pyha", "Qahs", "Qata", "Qhom", "Qhon", "Qhota", "Qih", "Qih", "Rhaq", "Rhaya", "Rhel", "Rhesh", "Rinh", "Rubh", "Sahja", "Tajih", "Tefh", "Thata", "Thya", "Tseh", "Tsimh", "Tsubh", "Tyago", "Tyo", "Una", "Urha", "Vhaso", "Wyra", "Xau", "Xheh", "Yehn", "Yhah", "Yhom", "Yonah", "Zana", "Ziuz"];
var keeperMaleSuffix = ["'a", "'to", "'li", "'sae", "'ra", "'ir", "'wo", "'ya", "'zi", "'tan"];
var keeperFemaleFirstname = ["Amare", "Feechi", "Ekon", "Zana", "Isabi", "Jara", "Jafara", "Dalia", "Haji", "Sabra", "Sabrasa", "Kali", "Kalifa", "Imani", "Asha", "Ode", "Odi", "Luli", "Lulu", "Uma", "Umi", "Maha", "Mahana", "Bahati", "Baha", "Aada", "Abir", "Abena", "Abra", "Abree", "Abri", "Kadi", "Kadia", "Kaela", "Kaeli", "Maari", "Mabel", "Maci", "Maca", "Amh", "Bukah", "Cemi", "Daca", "Dhebi", "Giah", "Gota", "Hnaba", "Jihli", "Kehda", "Kheni", "Khloe", "Khona", "Khuja", "Khuma", "Kiht", "Koh", "Lalah", "Leih", "Lhei", "Lho", "Masha", "Masya", "Mauh", "Mhih", "Mholi", "Miah", "Mikh", "Monh", "Muijh", "Naih", "Ngha", "Nhagi", "Nhago", "Nheu", "Nozih", "Oah", "Oghii", "Okhi", "Osha", "Pahja", "Panha", "Pawah", "Pelhi", "Pimoh", "Poki", "Pyha", "Qata", "Qhota", "Qina", "Raih", "Rhaya", "Rhel", "Rhela", "Rhoe", "Sahja", "Sami", "Seda", "Senah", "Sizha", "Tahla", "Tajih", "Thata", "Thya", "Una", "Urha", "Vhaso", "Wyra", "Xau", "Xheh", "Yhah", "Yonah", "Zana"];
var keeperSurname = ["Akhabila", "Amariyo", "Anbolho", "Awandah", "Bajhiri", "Betwanhe", "Binbotaj", "Burwani", "Chalahko", "Chelewae", "Dakwhil", "Dolabnha", "Elakha", "Entialpoh", "Epocan", "Fashonti", "Gamduhla", "Ganajai", "Garanjy", "Jaab", "Jakkya", "Jawantal", "Jinjahl", "Jomalah", "Kaatapoh", "Khamazom", "Lanbatal", "Lihzeh", "Lyehga", "Maimhov", "Mewrilah", "Mhakaracca", "Molkoh", "Molkot", "Moshantu", "Moshroca", "Mujuuk", "Nbolo", "Nelhah", "Panipahr", "Polaali", "Quowaital", "Rabntah", "Relanah", "Tayuun", "Wahcondalo", "Wilzuun", "Wolndara", "Zhwan", "Nbala" ];

// ******** PLAINSFOLK LALAFELL *******
// See below for names

// ******** DUNESFOLK LALAFELL *******
// See below for names

// ******* SEA WOLF ROEGADYN ******
var seawolfNames = ["Abar", "Abyl", "Aent", "Aerg", "Aerm", "Aerst", "Agat", "Agynn", "Ahl", "Ahld", "Ahr", "Ahrm", "Aht", "Ahtza", "Alyr", "Ask", "Ais", "Anka", "Ansa", "Aren", "Awyr", "Baen", "Bhir", "Bhrat", "Blan", "Blaet", "Bloe", "Blyss", "Blyn", "Bluom", "Brem", "Braen", "Bran", "Born", "Broes", "Boes", "Brot", "Bryda", "Byrg", "Byrgin", "Byrm", "Bylg", "Byrt", "Caepf", "Caer", "Ceig", "Cwaen", "Cwin", "Dani", "Daeg", "Denkyr", "Dehm", "Doen", "Does", "Dornn", "Dorpf", "Draeg", "Draga", "Drys", "Dyn", "Dyrf", "Dyrst", "Eidin", "Eifa", "Elak", "Elil", "Ent", "Erna", "Ewan", "Eyha", "Eyhil", "Eyn", "Eyri", "Edz", "Eynli", "Faeld", "Falk", "Farr", "Fatyr", "Fhil", "Fhis", "Fian", "Firk", "Flaz", "Flekk", "Floeg", "Floer", "Floh", "Foer", "Foet", "Fohc", "Folg", "Froe", "Froa", "Frusk", "Frut", "Fryd", "Fryn", "Fyr", "Fyst", "Gaez", "Ganz", "Gara", "Geim", "Germa", "Ghim", "Glac", "Glaz", "Goht", "Ghota", "Graeb", "Grein", "Grina", "Grym", "Gryne", "Hald", "Harr", "Hart", "Himal", "Hint", "Hirks", "Hyrks", "Holas", "Holl", "Horsk", "Horsam", "Hort", "Isil", "Keten", "Khan", "Khezl", "Kirz", "Klyng", "Knod", "Koen", "Krepf", "Koena", "Laent", "Lago", "Lamm", "Lahz", "Leita", "Liht", "Loet", "Loef", "Lorh", "Lora", "Lydir", "Lubd", "Loug", "Mhol", "Merl", "Marm", "Mhud", "Moeg", "Moen", "Moer", "Mynd", "Myte", "Nahct", "Nebb", "Nedyr", "Noez", "Nort", "Nortyr", "Nyst", "Oebb", "Oefyr", "Oeya", "Ofan", "Opyl", "Orn", "Ost", "Oyura", "Orr", "Pfar", "Pfrew", "Pfef", "Pfyn", "Phati", "Rael", "Raen", "Raeng", "Raet", "Ramm", "Rhen", "Rheti", "Rhit", "Rhyl", "Roegon", "Roega", "Roeh", "Ronth", "Ronn", "Rostn", "Ruht", "Ryhmm", "Ryss", "Saelb", "Saelz", "Saem", "Saes", "Skal", "Skapf", "Skrat", "Skoen", "Skarn", "Skal", "Skart", "Skeit", "Spart", "Solk", "Spaer", "Some", "Soemir", "Smyd", "Spyr", "Sthal", "Sthan", "Stral", "Stymm", "Styrn", "Swys", "Swysta", "Swar", "Sweig", "Syk", "Sylb", "Syng", "Syngi", "Syz", "Syzn", "Thor", "Thosin", "Thota", "Thuba", "Thubyr", "Toega", "Trahg", "Trachyn", "Toum", "Todd", "Thuv", "Ulm", "Ubyl", "Und", "Urs", "Usyn", "Unta", "Und", "Ubyl", "Waeb", "Waek", "Waem", "Waht", "Wakk", "Wall", "Wann", "Weitz", "Whad", "Wezzn", "Weitz", "Wist", "Wistyr", "Wunt", "Woll", "Wolk", "Woerd", "Wilf", "Wurt", "Wyb", "Wyrka", "Wyrk", "Wyda", "Wyrst", "Wyss", "Wyta", "Wyzn", "Ybolg", "Zaen", "Zaes", "Zagyl", "Zahr", "Zant", "Zedyr", "Zent", "Zirn", "Zoenig", "Zoer", "Zwelf", "Zwyn"];
var seawolfMaleSurname = "syn";
var seawolfFemaleSurname = "wyn";
var seawolfFemaleSuffix = ["swys", "thota", "wyda", "geim", "wyb", "rael", "lona", "bryda"];

// ******** HELLSGUARD ROEGADYN ********
var hellsguardMaleNames = ["Damp", "Blaring", "Faint", "Hoarse", "Hissing", "Husky", "Loud", "Azure", "Black", "Blue", "Brown", "Crimson", "Dark", "Dull", "Giant", "Great", "Immense", "Broad", "Crooked", "Deep", "Brief", "Early", "Ample", "Copious", "Abrasive", "Countless", "Eager", "Gentle", "Polite", "Obedient", "Zealous", "Proud", "Angered", "Angry", "Strong", "Obnoxious", "Colossal", "Huge", "Large", "Scrawny", "Tiny", "Immense", "Hefty", "Bestial", "Lofty", "Heavy", "Alert", "Vast", "Fearless", "Brave", "Faulty", "Unruly", "Jittery", "Billowy", "Erratic", "Rebel", "Busy", "Defiant", "Macho", "Smooth", "Witty", "Measly", "Bent", "Terrible", "Wise", "Purring", "White", "Red", "Yellow", "Orange", "Green", "Purple", "Eight", "Deep", "Psychotic", "Upset", "Garrulous", "Horrible", "Unsightly", "Labored", "Hospitable", "Ugly", "Tacit", "True", "Lying", "Alluring", "Truculent", "Spectacular", "Shallow", "Lush", "Old", "Macabre", "Onerous", "Wicked", "Ragged", "Upbeat", "Elegant", "Solid", "Secretive", "Aquatic", "Smoggy", "Jazzy", "Rapid", "Determined", "Thankful", "Graceful", "Weary", "Magenta", "Maroon", "Curious", "Four", "Befitting", "Deadpan", "Assorted", "Fluffy", "Fluttering", "Wiry", "Bizarre", "Simple", "Puzzling", "Elfin", "Royal", "Curved", "Nippy", "Ancient", "Hard", "Homely", "Cuddly", "Ablaze", "Freezing", "Frosted", "Devilish", "Gifted", "Loose", "Helpless", "Wandering", "Trite", "Relieved", "Secret", "Mute", "Abnormal", "Motionless", "Swift", "Sacred", "Honest", "Honored", "Crashing", "Thrashing", "Raging", "Heated", "Cooked", "Screaming", "Yelling", "Electric", "Thin", "Super", "Maddened", "Maddening", "Stinged", "Stingy", "Fresh", "Flimsy", "Neat", "Cumbersome", "Caring", "Cared", "Boorish", "Bright"];
var hellsguardFemaleNames = ["Fun", "Blue", "Azure", "Brunette", "Blonde", "Brown", "Orange", "Purple", "Violet", "Pink", "Yellow", "Sunny", "Silent", "Weeping", "Quiet", "Blossoming", "Short", "Happy", "Charming", "Elegant", "Swift", "Soft", "Deft", "Deaf", "Lithe", "Elfen", "Big", "Large", "Colossal", "Towering", "Massive", "Smart", "Intelligent", "Learned", "Scholarly", "Interesting", "Attractive", "Heavy", "Polite", "Next", "True", "Honest", "Honorable", "Courageous", "Open", "Pleasant", "Famous", "Comical", "Comfortable", "Weak", "Strong", "Monstrous", "Savage", "Grim", "Dire", "Deathly", "Willowing", "Sick", "Sincere", "Modern", "Thin", "Splendid", "Sad", "Empty", "Nice", "Sweet", "Sweetened", "Sour", "Soured", "Old", "Aged", "Tired", "Devoured", "Situated", "Sated", "Affectionate", "Ambitious", "Lucky", "Consceintious", "Curious", "Unhappy", "Generous", "Furious", "Serious", "Fearful", "Faulty", 'Unlucky', "Active", 'Attentive', 'New', 'Naive', 'Sporty', 'Athletic', 'Agile', 'Graceful', 'Intuitive', 'Dearing', 'Expensive', 'Full', 'Foreign', 'Lightly', 'Lighted', 'Darkened', 'Darkly', 'Sickly', 'Ill', 'Ancient', 'Elden', 'Lowly', 'High', 'Stunning', 'Favorite', 'Fresh', 'Frank', 'Worried', 'Long', 'Dry', 'Secret', 'Secretive', 'Fair', 'Loyal', 'Luscious', 'Sensical', 'Selfless', 'Driven', 'Knowing', 'Mature', 'Feminine', 'Female', 'Fiesty', 'Beloved', 'Foxy', 'Observant', 'Outgoing', 'Patient', 'Tender', 'Tawny', 'Sultry', 'Cheeky', 'Cheerful', 'Bewitching', 'Bewitched', 'Cursed', 'Cursing', 'Doting', 'Intoxicating', 'Toxic', 'Youthful', 'Radiant', 'Ravishing', 'Idolized', 'Proud', 'Fickle', 'Peevish', 'Picky', 'Wretched', 'Vain', 'Stubborn', 'Sneaky', 'Cruel', 'Cynical', 'Deceptive', 'Cold'];
var hellsguardMaleSurnames = ['Actor', 'Author', 'Bachelor', 'Boy', 'Brother', 'Conductor', 'Count', 'Dad', 'Father', 'Duke', 'Man', 'Emperor', 'Father', 'Grandfather', 'Heir', 'Hero', 'Host', 'Husband', 'King', 'Master', 'Murderer', 'Nephew', 'Poet', 'Prince', 'Sir', 'Son', 'Uncle', 'Wizard', 'Waiter', 'Baby', 'Bird', 'Cat', 'Cattle', 'Child', 'Companion', 'Comrade', 'Cousin', 'Dancer', 'Deer', 'Friend', 'Guardian', 'Guest', 'Owner', 'Parent', 'Passenger', 'Hog', 'Pupil', 'Scholar', 'Relative', 'Swan', 'Buck', 'Stallion', 'Boar', 'Rooster', 'Drake', 'Bull', 'Gander', 'Fox', 'Tiger', 'Lion', 'Hound', 'Monster', 'Devil', 'Mountain', 'Pillar', 'Rock', 'Boulder', 'Strand', 'Strait', 'Blade', 'Axe', 'Hammer', 'Warhammer', 'Mace', 'Scythe', 'Dagger', 'Staff', 'Trident', 'Pike', 'Wall', 'Fortress', 'Keep', 'Chain', 'Beast', 'Demon', 'Goat', 'Ship', 'Mast', 'Cloud', 'Storm', 'Tornado', 'Hurricane', 'Rain', 'Wind', 'Lightning', 'Thunder', 'Scream', 'Yell', 'Sound', 'Boom', 'Time', 'Leather', 'Plate', 'Armor', 'Hide', 'Artist', 'Engineer', 'Mirror', 'Fire', 'Waterfall', 'Leaf', 'Forest', 'Building', 'Home', 'Demise', 'Doom', 'Reckoning', 'Revenge', 'Death', 'Havoc', 'Rage', 'Tank', 'Wolf', 'Dog', 'Bear', 'Coeurl', 'Sprout', 'Root', 'Trunk', 'Wood', 'Metal', 'Steel', 'Obsidian', 'Copper', 'Silver', 'Gold', 'Iron', 'Monk', 'Fist', 'Foot', 'Feet', 'Palm', 'Skull', 'Bone', 'Bones', 'Ribs', 'Knife', 'Bomb', 'Frost', 'Ice', 'Fire', 'Flame', 'Flames', 'Desecration', 'Deliverance', 'Defiance', 'Cleave', 'Slam', 'Choke', 'Rot', 'Pile', 'Corpse', 'Rodent', 'Mammett', 'Darkness', 'Light', 'Sun', 'Moon', 'Volcano', 'Lava', 'Scorch']; 
var hellsguardFemaleSurnames = ['Auk', 'Blackbird', 'Chickadee', 'Crow', 'Jay', 'Dove', 'Duck', 'Finch', 'Flycatcher', 'Gull', 'Tern', 'Hawk', 'Falcon', 'Heron', 'Hummingbird', 'Kingfisher', 'Nuthatcher', 'Owl', 'Parrot', 'Seabird', 'Shorebird', 'Sparrow', 'Swallow', 'Swift', 'Thrush', 'Warbler', 'Woodpecker', 'Wren', 'Oriole', 'Quail', 'Grosbeak', 'Coot', 'Goldeneye', 'Goose', 'Witch', 'Oracle', 'Seer', 'Aconite', 'Anemone', 'Allium', 'Ageratum', 'Angelica', 'Angelonia', 'Azalea', 'Balm', 'Lily', 'Bellflower', 'Begonia', 'Heart', 'Mouse', 'Mammett', 'Nutkin', 'Weed', 'Buttercup', 'Bugloss', 'Bell', 'Poppy', 'Bean', 'Mint', 'Carnation', 'Rose', 'Bud', 'Sprout', 'Leaf', 'Tree', 'Oak', 'Pine', 'Thistle', 'Chive', 'Sage', 'Coleus', 'Cleome', 'Daffodil', 'Dahlia', 'Daisy', 'Crown', 'Imperial', 'Tuft', 'Fennel', 'Grass', 'Foxglove', 'Iris', 'Mantle', 'Ladder', 'Pulpit', 'Cotton', 'Leadwart', 'Lavendar', 'Maiden', 'Daughter', 'Princess', 'Mother', 'Aunt', 'Lady', 'Woman', 'Dancer', 'Priestess', 'Scholar', 'Warrior', 'Hound', 'Monster', 'Demon', 'Hammmer', 'Sword', 'Blade', 'Shield', 'Hill', 'Seed', 'Moonflower', 'Moon', 'Sun', 'Wave', 'Waves', 'Pansy', 'Flax', 'Petunia', 'Periwinkle', 'Duchess', 'Innocence', 'Snow', 'Snowdrop', 'Hale', 'Ice', 'Fire', 'Frost', 'Woodruff', 'Tulip', 'Senna', 'Violet', 'Yarrow', 'Archangel', 'Loosestrife', 'Zinnia', 'Almond', 'Pecan', 'Papaya', 'Beech', 'Willow', 'Sequoia', 'Locust', 'Birch', 'Ash', 'Laurel', 'Coconut', 'Banana', 'Popoto', 'Spruce', 'Magnolia', 'Fig', 'Caprea', 'Pine', 'Walnut', 'Honey', 'Hive', 'Maple', 'Breadfruit', 'Nutmeg', 'Lightning', 'Thunder', 'Wind', 'Earth', 'Soil', 'Water', 'Swamp', 'Murk', 'Mire', 'Beach', 'Coast', 'Sand', 'Jungle', 'Mist', 'Fog', 'Moss', 'Lichen', 'Mistletoe'];

// ********* ELEZEN (Duskwight & Wildwood) ********
var elezenMaleNames = ['Alain', 'Alixandre', 'Artur', 'Aymon', 'Benedeit', 'Bernart', 'Barnadaoux', 'Barnadoe', 'Brandan', 'Charlon', 'Christian', 'Charlaux', 'Charloix', 'Aurifort', 'Raitmaeaux', 'Mourechaux', 'Nogeloix', 'Padilloux', 'Louisoix', 'Euganaire', 'Bertennaunt', 'Edwaine', 'Edwart', 'Edmont', 'Edmaine', 'Estiene', 'Estaine', 'Francoix', 'Franaux', 'Francaux', 'Franceis', 'Galtier', 'Galtoix', 'Galtiea', 'Gefrei', 'Gefraixe', 'Gerart', 'Germont', 'Filebert', 'Gilebert', 'Gregoire', 'Gregoix', 'Gaulter', 'Guillalme', 'Guillame', 'Guillaume', 'Guion', 'Guiox', 'Guiot', 'Henrimont', 'Henraie', 'Henraine', 'Henroix', 'Heraut', 'Herbert', 'Hermonte', 'Hermont', 'Hubert', 'Hughlaine', 'Hugone', 'Jasquie', 'Jasque', 'Jasqiox', 'Jehan', 'Jermont', 'Leonarde', 'Leomonte', 'Leomont', 'Leoforte', 'Loeis', 'Lohier', 'Lohaine', 'Marco', 'Marciox', 'Marcmont', 'Martine', 'Martaine', 'Martae', 'Michiele', 'Michiel', 'Mickaile', 'Oliver', 'Olivaine', 'Oliviox', 'Osmont', 'Osmonte', 'Peire', 'Peiaire', 'Peiaine', 'Perceval', 'Percevale', 'Perceviox', 'Phelipe', 'Phelmonte', 'Polaine', 'Raolaine', 'Raol', 'Raolmonte', 'Renalde', 'Reinald', 'Renaile', 'Reniox', 'Richarde', 'Richart', 'Rickmont', 'Rickmonte', 'Roberte', 'Robaine', 'Rolant', 'Rolante', 'Roilante', 'Sanson', 'Sanmonte', 'Samuele', 'Thiebaut', 'Thiebiox', 'Thiemonte', 'Tristane', 'Tristan', 'Tristran', 'Tristram', 'Tristrume', 'Tumas', 'Thomase', 'Thomonte', 'Wace', 'Walkelin', 'Walkeline', 'Walkelaine', 'Willalme', 'Williame', 'Williox', 'Willmonte', 'Wilmont', 'Willeme', 'Yvaine', 'Yvain'];
var elezenFemaleNames = ['Aalis', 'Alys', 'Cecile', 'Cunstance', 'Constance', 'Ele', 'Gunnor', 'Mahelt', 'Marie', 'Marion', 'Nicolete', 'Ysabele', 'Aalisette', 'Aalisie', 'Alysette', 'Alysie', 'Elette', 'Elesie', 'Cecilie', 'Cunstancette', 'Gunnorette', 'Meheltie', 'Mariette', 'Marienne', 'Marionette', 'Nicolae', 'Ysellte', 'Yslie', 'Adeline', 'Adelette', 'Aimee', 'Alidette', 'Alidae', 'Amelie', 'Andree', 'Anna', 'Annette', 'Antoinette', 'Antoinie', 'Augusta', 'Agnes', 'Barbette', 'Baptistine', 'Adrienne', 'Albertine', 'Alinette', 'Anais', 'Angelina', 'Angellette', 'Anne', 'Antonia', 'Aurelie', 'Angele', 'Bernadette', 'Benoit', 'Adelaide', 'Alexandrine', 'Alixie', 'Anastasie', 'Angeline', "Anna-Marie", 'Antonine', 'Adolphine', 'Armandine', 'Berthe', 'Camille', 'Agathe', 'Alice', 'Alphonsine', 'Andrette', 'Andrea', 'Angelique', 'Annette', 'Armande', 'Adele', 'Augustine', 'Blanche', 'Carmen', 'Caroline', 'Claudine', 'Clare', 'Clotilde', 'Cecile', 'Denise', 'Delphinette', 'Emilie', 'Eleonore', 'Ernestine', 'Elalie', 'Esther', 'Evette', 'Eva', 'Florence', 'Florentine', 'Germaine', 'Gertrude', 'Francine', 'Honorine', 'Idette', 'Ida', 'Irma', 'Isabelle', 'Irene', 'Henriette', 'Gabrielle', 'Julienne', 'Juliette', 'Jeanne', 'Ledie', 'Lucia', 'Luxia', 'Marcelle', 'Mariette', 'Maleanie', 'Melina', 'Nathalie', 'Nelly', 'Paulette', 'Olfa', 'Pauline', 'Mathilde', 'Rolande', 'Victoria', 'Sophie', 'Sophiette', 'Suzanne', 'Sylvie', 'Victoire', 'Veronique', 'Virginie', 'Yvonne', 'Regina', 'Raymonde', 'Philomene', 'Simonne', 'Rachele', 'Etiennette', 'Elisabeth', 'Edith', 'Zoe'];
var elezenSurnames = ['Archambault', 'Augustin', 'Babineaux', 'Baudin', 'Beauchene', 'Beaufort', 'Beaulieu', 'Beaumont', 'Belanger', 'Bellerose', 'Belmonte', 'Bernardaux', 'Blanchelaux', 'Bonheur', 'Bonhomme', 'Bonnaire', 'Bonnette', 'Bonnaie', 'Boucharde', 'Bourreau', 'Brisbois', 'Brisbiox', 'Brodeur', 'Charbonneau', 'Charbonniox', 'Charbonnette', 'Charpentier', 'Charrone', 'Chastain', 'Clementte', 'Courtemanche', 'Cousineau', 'Couture', 'Deschamps', 'Descoteaux', 'Desjardins', 'Desroches', 'Desrosiers', 'Duchamps', 'Dufortte', 'Dumontte', 'Fabieniox', 'Faucheux', 'Duvallaie', 'Forestier', 'Fournier', 'Gagneux', 'Gagnone', 'Gardinier', 'Garnier', 'Gauthier', 'Germaine', 'Germain', 'Geroux', 'Gosselinae', 'Guillory', 'Herbertte', 'Jacquesette', 'Lachance', 'Lachapelle', 'Lamarre', 'Lambertte', 'Langlais', 'Langlois', 'Langliox', 'Lapointe', 'Laurentte', 'Lavigne', 'Lavoie', 'Leandre', 'Leandrette', 'Legrand', 'Legrande', 'Lemaire', 'Lemieux', 'Lesauvage', 'Lestrange', 'Leveque', 'Lyonette', 'Lyon', 'Marion', 'Martelle', 'Massonae', 'Mathieu', 'Mercier', 'Mercieae', 'Michaud', 'Monet', 'Monette', 'Monniliox', 'Neuville', 'Nicolas', 'Olivier', 'Oliviae', 'Noyer', 'Noyette', 'Palomer', 'Palomae', 'Paquet', 'Parentte', 'Pelle', 'Perigord', 'Perigorde', 'Perreault', 'Perranault', 'Perrote', 'Pierre', 'Plamondon', 'Planque', 'Planche', 'Planchae', 'Plourde', 'Poingsestre', 'Porier', 'Porcher', 'Rayne', 'Rayniox', 'Raynaux', 'Renaud', 'Richarde', 'Richelieu', 'Roche', 'Roussaue', 'Rousellete', 'Roux', 'Salomne', 'Sauvage', 'Sauveterre', 'Severin', 'Severae', 'Sourdette', 'Tremplae', 'Tremblae', 'Victoriox', 'Vitoriaux', 'Voclain', 'Cilleneuve', 'Villeneuve', 'Treverre', 'Leveilleur', 'Lasserrant', 'Fortemps', 'Haillenarte', 'Augurelt', 'Danguolain', 'Durendaire', 'Dzemael'];

// ****** RAEN AU RA ********
var raenMaleFirstNames = ["Akagi", "Baien", 'Byakubu', 'Doware', 'Ensetsu', 'Fugetsu', 'Fukudo', 'Genbu', 'Gosetsu', 'Gyodo', 'Gyokusei', 'Hansaku', 'Hayabusa', 'Hien', 'Hiun', 'Hojo', 'Isse', 'Izuna', 'Kagero', 'Kagetora', 'Kaien', 'Kamui', 'Kansui', 'Karaku', 'Kasasagi', 'Kazan', 'Keiho', 'Keimei', 'Keiten', 'Kongo', 'Kyokuho', 'Masatsuchi', 'Motogoe', 'Murakumo', 'Nawashiro', 'Raiden', 'Rakuyo', 'Ransetsu', 'Rasho', 'Rino', 'Ryosen', 'Sagan', 'Saiun', 'Sakyo', 'Senryo', 'Sentei', 'Shiden', 'Shinto', 'Shiranami', 'Shirojishi', 'Shiun', 'Tansui', 'Tosetsu', 'Tougen', 'Tsukikage', 'Udoku', 'Ugan', 'Ugetsu', 'Ukyo', 'Unryu', 'Unzan', 'Usefushi', 'Yabusame', 'Yomei', 'Yusui', 'Zansei', 'Zansetsu', 'Zuiko', 'Yuki', 'Maeda', 'Manabe', 'Fusayuki', 'Sugi', 'Yamanoi', 'Nagatani', 'Aso', 'Kuroki', 'Mizuno', 'Shijou', 'Iwamura', 'Honjou', 'Nishi', 'Miyabe', 'Ishimaki', 'Takeda', 'Tozawa', 'Abe', 'Ando', 'Honda', 'Hirose', 'Monoe', 'Ito'];
var raenFemaleNames = ['Ajisai', 'Anzu', 'Aoi', 'Atori', 'Awayuki', 'Ayame', 'Azami', 'Azena', 'Botan', 'Chidori', 'Chigusa', 'Chihaya', 'Enrei', 'Furan', 'Haname', 'Hazakura', 'Hibari', 'Ibara', 'Ibuki', 'Isuka', 'Izayoi', 'Kaede', 'Kagetsu', 'Kasumi', 'Kikusui', 'Kikyo', 'Kogyoku', 'Koharu', 'Komachi', 'Koruri', 'Kotokaze', 'Kototsuki', 'Kozakura', 'Kuina', 'Kumokiri', 'Kurenai', 'Mahiwa', 'Makoto', 'Mana', 'Manazuru', 'Mine', 'Misago', 'Mitsuba', 'Mizuki', 'Mozu', 'Narumi', 'Natsume', 'Ochimi', 'Sayo', 'Sazanami', 'Seika', 'Sekka', 'Shion', 'Sui', 'Sumire', 'Suzume', 'Tobana', 'Tsubaki', 'Tsugumi', 'Ume', 'Uto', 'Waka', 'Yachiyo', 'Yayoi', 'Yomi', 'Yozakura', 'Yuki', 'Zakuro', 'Aguri', 'Ai', 'Aka', 'Akai', 'Akii', 'Ama', 'Ane', 'Asa', 'Baba', 'Ben', 'Bin', 'Bo', 'Chiki', 'Chima', 'Chin', 'Chiyo', 'Fude', 'Furi', 'Fume', 'Fuso', 'Futsu', 'Hama', 'Hana', 'Hatsu', 'Heya', 'Hiina', 'Hiki', 'Hiko', 'Haru', 'Gin', 'Kase', 'Kawa', 'Katsu', 'Kaya', 'Kayo', 'Kesai', 'Kiku', 'Kichi', 'Kina', 'Kinu', 'Kiri', 'Kiysu', 'Kiyo', 'Koya', 'Kogo', 'Ko', 'Kuri', 'Kusu', 'Kuwa', 'Mako', 'Maki', 'Machi', 'Mane', 'Mare', 'Mari', 'Masa', 'Mimi', 'Mitsu', 'Mochi', 'Moku', 'Momo', 'Muma', 'Mume', 'Mutsu', 'Nabe', 'Nagu', 'Nai', 'Naka', 'Nana', 'Natsu', 'Nei', 'Neko', 'Oshi', 'Riyo', 'Rusu', 'Saka', 'Sai', 'Sago', 'Sani', 'Saru', 'Satsu', 'Sawa', 'Rin', 'Riyo', 'Tsuka', 'Tsuji', 'Tsune', 'Tsushi', 'Tsuta', 'Uma', 'Ume', 'Uno', 'Ushi', 'Uta', 'Yama', 'Yaya', 'Yome', 'Yuki', 'Yuti', 'Yuri', 'Yuwa', 'Yono', 'Yuna'];
var raenSurnames = ['Abumi', 'Akagane', 'Akiudo', 'Aogane', 'Bakuro', 'Banjo', 'Benitoki', 'Bugai', 'Buhen', 'Bunja', 'Chosai', 'Daisho', 'Daito', 'Dejiki', 'Doshin', 'Edakumi', 'Fukiku', 'Furukane', 'Gakunin', 'Gakuto', 'Godo', 'Gunji', 'Gyoji', 'Hagane', 'Hakuuchi', 'Hatasashi', 'Ishiku', 'Iteya', 'Ittetsu', 'Jizutsu', 'Kabuto', 'Kaifu', 'Kaisuri', 'Kaneuchi', 'Kanshi', 'Kasanui', 'Kataribe', 'Kaujin', 'Kawanami', 'Kazarishi', 'Kensaki', 'Kiba', 'Kodakumi', 'Kogane', 'Kurogane', 'Kusakari', 'Kusushi', 'Maibito', 'Meiken', 'Mihata', 'Miyumi', 'Mizuhiki', 'Musa', 'Naeuri', 'Nagae', 'Obinata', 'Okeya', 'Onishi', 'Oshidari', 'Oshiga', 'Ritsuso', 'Rokuyari', 'Sakimuri', 'Sarugaku', 'Sashihai', 'Shibunuri', 'Shikibu', 'Shirogane', 'Tabito', 'Tachikake', 'Tanshi', 'Tatewaki', 'Torioi', 'Tosho', 'Tsurugi', 'Tsuwamono', 'Urabe', 'Urabito', 'Ushikai', 'Yatsurugi', 'Yumishi', 'Yumite', 'Yumitori', 'Yuzuka', 'Minamoto', 'Daigo', 'Fukakusa', 'Nijo', 'Saga', 'Sanjo', 'Shirakawa', 'Juntoku', 'Kameyama', 'Kazan', 'Koko', 'Montoku', 'Murakami', 'Ninmyo', 'Ogimachi', 'Reizei', 'Seiwa', 'Kawachi', 'Settsu', 'Yamato',  'Uda', 'Yozei', 'Taira', 'Kanmu', 'Bando', 'Heishi', 'Fujiwara', 'Hokke', 'Kyoke', 'Nanke', 'Shikeke', ];


// ****** XAELA AU RA *******
var xaelaMaleNames = ['Abaka', 'Achujim', 'Adarkidai', 'Adkiragh', 'Agasiletai', 'Agsaldai', 'Agujam', 'Alchigh', 'Alghu', 'Amasandji', 'Amasar', 'Ambaghai', 'Anarba', 'Arabuccha', 'Aragibal', 'Argasar', 'Arik', 'Arslang', 'Aruktai', 'Baatu', 'Baavgai', 'Bagaridai', 'Baidar', 'Baidur', 'Bardam', 'Batacaciqan', 'Batachikhan', 'Bayan', 'Bayar', 'Begugtei', 'Bucharan', 'Budjek', 'Bugunutei', 'Bujeg', 'Bujir', 'Bukidai', 'Bulqadar', 'Bultechu', 'Bultger', 'Bulugan', 'Buqatai', 'Buyantu', 'Caragai', 'Chaghadai', 'Chaghagan', 'Chanar', 'Charakha', 'Chidukhul', 'Chigu', 'Chilagun', 'Chiledu', 'Chilger', 'Chiluku', 'Chormagan', 'Chuacenur', 'Chulgetei', 'Daidukul', 'Delbeg', 'Dorbei', 'Emlig', 'Esugen', 'Guyug', 'Hooshal', 'Ilugei', 'Iturgen', 'Jagadai', 'Jamugha', 'Jebei', 'Jebke', 'Jelme', 'Jenkshi', 'Kaishan', 'Khaidai', 'Khal', 'Khalja', 'Khuchar', 'Kishiligh', 'Kuyuk', 'Kuzhuk', 'Ligdan', 'Luvsan', 'Maqali', 'Masgud', 'Mauci', 'Munglig', 'Ogodei', 'Ozbeg', 'Qoribucha', 'Shilugei', 'Shiramun', 'Sidurgu', 'Sukegei', 'Tamachag', 'Teleboge', 'Tordung', 'Tsagaday', 'Uchikin', 'Udutai', 'Yabuqa', 'Yerentai', 'Batjargal', 'Monkhbat', 'Ganbaatar', 'Narantsetseg', 'Ganzorig', 'Enkhjargal', 'Ganbold', 'Gantulga', 'Bolormaa', 'Batbayar', 'Otgonbayar', 'Altan', 'Bataar', 'Batu', 'Batukhan', 'Chingis', 'Chinua', 'Chuluun', 'Dzhambul', 'Erden', 'Khan', 'Medekhgui', 'Nekhii', 'Och', 'Odgerel', 'Ogtbish', 'Oktai', 'Qadan', 'Sukh', 'Sukhbataar', 'Taban', 'Tarkhan', 'Terbish', 'Timur', 'Tomorbataar', 'Ulagan', 'Xanadu', 'Yul'];
var xaelaFemaleNames = ['Alagh', 'Alan', 'Alt', 'Altani', 'Altun', 'Alun', 'Anggir', 'Bagurchi', 'Barghujin', 'Baugurchi', 'Beki', 'Berude', 'Bodo', 'Boljigchi', 'Boragchin', 'Borogchin', 'Boroqcin', 'Borte', 'Botokhui', 'Caalun', 'Caur', 'Ceceyigen', 'Chabi', 'Chagur', 'Chakha', 'Chambui', 'Checheyigen', 'Cherbin', 'Chotan', 'Cirina', 'Cota', 'Cotan', 'Cotota', 'Dagasi', 'Doquz', 'Dorgene', 'Dorgono', 'Doyi', 'Ebegei', 'Eji', 'Eke', 'Emegen', 'Gergei', 'Ghoa', 'Gorbeljin', 'Gurbesu', 'Guua', 'Hoelun', 'Hogelun', 'Holuikhan', 'Hujaghur', 'Hujaur', 'Ibakha', 'Jaliqai', 'Khadagan', 'Khatun', 'Khogaghchin', 'Khojin', 'Khorchi', 'Khorijin', 'Khugurchin', 'Khulan', 'Koko', 'Maral', 'Mergen', 'Mide', 'Narengawa', 'Nigen', 'Nomolun', 'Ogelen', 'Oghul', 'Ogul', 'Oki', 'Orbei', 'Orghana', 'Qatun', 'Qoyar', 'Samga', 'Sechen', 'Shar', 'Sokhatai', 'Sorkhaghtani', 'Sorocan', 'Surkukteni', 'Suvd', 'Tacchotan', 'Tarqun', 'Tegusken', 'Temulun', 'Togene', 'Toragana', 'Toregene', 'Tsenxer', 'Turakina', 'Ucugen', 'Ujin', 'Ulan', 'Yesuntei' ];
var xaelaSurnames = ['Adarkim', 'Angura', 'Arulaq', 'Avagnar', 'Bairon', 'Bayaqud', 'Bolir', 'Borlaaq', 'Buduga', 'Chaghan', 'Dalamiq', 'Dataq', 'Dazkar', 'Dhoro', 'Dotharl', 'Ejinn', 'Geneq', 'Gesi', 'Gharl', 'Goro', 'Haragin', 'Himaa', 'Horo', 'Iriq', 'Jhungid', 'Kagon', 'Kahkol', 'Kha', 'Kharlu', 'Khatayin', 'Malaguld', 'Malqir', 'Mankhad', 'Mierqid', 'Moks', 'Mol', 'Noykin', 'Olkund', 'Orben', 'Orl', 'Oronir', 'Oroq', 'Qalli', 'Qestir', 'Qerel', 'Sagahl', 'Torgud', 'Tumet', 'Ugund', 'Ura', 'Urumet', 'Uyagir'];





// ****** RANDOM NAME GENERATOR *******
document.getElementById('btn').addEventListener('click', function(){
    // var race = document.getElementById('races');
    // var gender = document.getElementById('gender');
    let raceOption = document.getElementById("races").value;
    let genderOption = document.getElementById("gender").value;
    // Midlander vars
    let randomHyurMale = Math.floor(Math.random() * midlanderMaleFirstname.length);
    let randomHyurFemale = Math.floor(Math.random() * midlanderFemaleFirstname.length);
    let randomHyurSurname = Math.floor(Math.random() * midlanderSurname.length); 
    // Highlander vars
    let randomHighMale = Math.floor(Math.random() * highlanderMaleFirstname.length);
    let randomHighFemale = Math.floor(Math.random() * highlanderFemaleFirstname.length);
    let randomHighSurname = Math.floor(Math.random() * highlanderSurname.length); 
    // Seeker vars
    let randomSeekerMale = Math.floor(Math.random() * seekerMaleFirstname.length); 
    let randomSeekerFemale = Math.floor(Math.random() * seekerFemaleFirstname.length);
    let randomSeekerMaleSurname = Math.floor(Math.random() * seekerMaleSurname.length);
    let randomSeekerFemaleSurname = Math.floor(Math.random() * seekerFemaleSurname.length);
    // Keeper vars
    let randomKeeperMale = Math.floor(Math.random() * keeperMaleFirstname.length); 
    let randomKeeperSuffix = Math.floor(Math.random() * keeperMaleSuffix.length);
    let randomKeeperFemale = Math.floor(Math.random() * keeperFemaleFirstname.length);
    let randomKeeperSurname = Math.floor(Math.random() * keeperSurname.length);
    // Hellsguard vars
    let randomHellsguardMaleFirstName = Math.floor(Math.random() * hellsguardMaleNames.length); 
    let randomHellsguardMaleSurname = Math.floor(Math.random() * hellsguardMaleSurnames.length); 
    let randomHellsguardFemaleFirstName = Math.floor(Math.random() * hellsguardFemaleNames.length); 
    let randomHellsguardFemaleSurname = Math.floor(Math.random() * hellsguardFemaleSurnames.length); 
    // Elezen vars
    let randomElezenMaleName = Math.floor(Math.random() * elezenMaleNames.length); 
    let randomElezenFemaleName = Math.floor(Math.random() * elezenFemaleNames.length); 
    let randomElezenSurname = Math.floor(Math.random() * elezenSurnames.length); 
    // Raen vars
    let randomRaenMaleName = Math.floor(Math.random() * raenMaleFirstNames.length);
    let randomRaenFemaleName = Math.floor(Math.random() * raenFemaleNames.length);
    let randomRaenSurnames = Math.floor(Math.random() * raenSurnames.length);
    //  Xaela vars
    let randomXaelaMaleName = Math.floor(Math.random() * xaelaMaleNames.length);
    let randomXaelaFemaleName = Math.floor(Math.random() * xaelaFemaleNames.length);
    let randomXaelaSurname = Math.floor(Math.random() * xaelaSurnames.length);

    // Midlanders
    if(raceOption === 'midlander' && genderOption === 'male'){
        document.querySelector('.name').innerHTML= midlanderMaleFirstname[randomHyurMale] + " " + midlanderSurname[randomHyurSurname];
        
    } else if (raceOption === 'midlander' && genderOption === 'female') {
        document.querySelector('.name').innerHTML= midlanderFemaleFirstname[randomHyurFemale] + " " + midlanderSurname[randomHyurSurname];

    // Highlanders
    } else if(raceOption === 'highlander' && genderOption === 'male'){
        document.querySelector('.name').innerHTML= highlanderMaleFirstname[randomHighMale] + " " + highlanderSurname[randomHighSurname];
    } else if(raceOption === 'highlander' && genderOption === 'female'){
        document.querySelector('.name').innerHTML= highlanderFemaleFirstname[randomHighFemale] + " " + highlanderSurname[randomHighSurname];

    //Seeker of the Sun 
    }else if(raceOption === 'seeker-of-the-sun' && genderOption === 'male'){
        document.querySelector('.name').innerHTML= seekerMaleFirstname[randomSeekerMale] + " " + seekerMaleSurname[randomSeekerMaleSurname];
    } else if(raceOption === 'seeker-of-the-sun' && genderOption === 'female'){
        document.querySelector('.name').innerHTML= seekerFemaleFirstname[randomSeekerFemale] + " " + seekerFemaleSurname[randomSeekerFemaleSurname];

    // Keeper of the Moon
    } else if(raceOption === 'keeper-of-the-moon' && genderOption === 'male'){
        document.querySelector('.name').innerHTML= keeperMaleFirstname[randomKeeperMale] + keeperMaleSuffix[randomKeeperSuffix] + ' ' + keeperSurname[randomKeeperSurname];
    } else if(raceOption === 'keeper-of-the-moon' && genderOption === 'female'){
        document.querySelector('.name').innerHTML= keeperFemaleFirstname[randomKeeperFemale] + " " + keeperSurname[randomKeeperSurname];
    // Plainsfolk Lalafell 
    } else if (raceOption === 'plainsfolk' && genderOption === 'male'){
        
        for (let i = 0; i <= 1; i++){
            var plainsfolkA = ["Zo", "Mo", "Ko", "Yor", "Wa", "Wo", "Al", "Ala", "Wi", "No", "Bo", "Ba", "Rara", "Ra", "Ma", "Re", "Ro", "Ru", "Pi", "Po", "Pu", "Ji", "Jo", "Ja", "Ju", "Ki", "Ka", "Ku", "Li", "La", "Le", "Mal", "Vi", "Ve", "Va"];
            var plainsfolkMaleB = ["ka", "pel", "rido", "guda", "guga", "yaga", "yada", "yara", "tara", "taru", "tari", "para", "paro", "pari", "maga", "magi", "mago", "yori", "yogi", "yobi", "yari", "maru", "nari", "naru", "naro", "to", "ti", "toko", "toka", "toke", "li", "la", "lapa", "lopa", "laka", "lama", "waka", "bagu", "baga", "bama", "bara", "baru", "bari", "tar", "ta", "lo", "ku", "nu", "na",];
            var plainsfolkMaleC = ["Zo", "Mo", "Ko", "Yor", "Wa", "Wo", "Al", "Ala", "Wi", "No", "Bo", "Ba", "Rara", "Ra", "Ma", "Re", "Ro", "Ru", "Pi", "Po", "Pu", "Ji", "Jo", "Ja", "Ju", "Ki", "Ka", "Ku", "Li", "La", "Le", "Mal", "Vi", "Ve", "Va"];
            var getMaleA = plainsfolkA.splice(Math.floor(Math.random()*plainsfolkA.length),1);
            var getMaleB = plainsfolkMaleB.splice(Math.floor(Math.random()*plainsfolkMaleB.length),1);
            var getMaleC = plainsfolkMaleC.splice(Math.floor(Math.random()*plainsfolkMaleC.length),1);
            document.querySelector('.name').innerHTML= getMaleA + getMaleB + ' ' + getMaleC + getMaleB;
            
        }
    } else if (raceOption === 'plainsfolk' && genderOption === 'female'){
        for (let i = 0; i <= 1; i++){
            var plainsfolkA = ["Zo", "Mo", "Ko", "Yor", "Wa", "Wo", "Al", "Ala", "Wi", "No", "Bo", "Ba", "Rara", "Ra", "Ma", "Re", "Ro", "Ru", "Pi", "Po", "Pu", "Ji", "Jo", "Ja", "Ju", "Ki", "Ka", "Ku", "Li", "La", "Le", "Mal", "Vi", "Ve", "Va"];
            var plainsfolkFemaleB = ["zo", "mo", "ko", "yor", "wa", "wo", "al", "ala", "wi", "no", "bi", "ba", "rara", "ra", "ma", "re", "ri", "ru", "pi", "pu", "ji", "jo", "ja", "ju", "ki", "ka", "ku", "li", "la", "le", "mal", "vi", "ve", "va"];
            var getFemaleA = plainsfolkA.splice(Math.floor(Math.random()*plainsfolkA.length),1);
            var getFemaleB = plainsfolkFemaleB.splice(Math.floor(Math.random()*plainsfolkFemaleB.length),1);
            document.querySelector('.name').innerHTML= getFemaleA + getFemaleB + getFemaleB + ' ' + getFemaleA + getFemaleB;
            
        }
    
    // Dunesfolk Lalafell  Male = AAB-CCB    Female = AAB-AB
    } else if (raceOption === 'dunesfolk' && genderOption === 'male'){
        for (let i = 0; i <= 1; i++){
            var dunesfolkA = ["Zo", "Mo", "Ko", "Yor", "Wa", "Wo", "Al", "Wi", "No", "Bo", "Ba", "Ra", "Ma", "Re", "Ro", "Ru", "Pi", "Po", "Pu", "Ji", "Jo", "Ja", "Ju", "Ki", "Ka", "Ku", "Li", "La", "Le", "Vi", "Ve", "Va"];
            var dunesfolkMaleB = ["rido", "guda", "guga", "yaga", "yada", "yara", "tara", "taru", "tari", "para", "paro", "pari", "maga", "magi", "mago", "yori", "yogi", "yobi", "yari", "maru", "nari", "naru", "naro", "toko", "toka", "toke", "lapa", "lopa", "laka", "lama", "waka", "bagu", "baga", "bama", "bara", "baru", "bari", "tar"];
            var dunesfolkMaleC = ["Zo", "Mo", "Ko", "Yor", "Wa", "Wo", "Al", "Ala", "Wi", "No", "Bo", "Ba", "Ra", "Ma", "Re", "Ro", "Ru", "Pi", "Po", "Pu", "Ji", "Jo", "Ja", "Ju", "Ki", "Ka", "Ku", "Li", "La", "Le", "Ma", "Vi", "Ve", "Va"];
            var getMaleA = dunesfolkA.splice(Math.floor(Math.random()*dunesfolkA.length),1);
            var getMaleATwo = getMaleA.toLocaleString().toLowerCase().split(',');
            var getMaleB = dunesfolkMaleB.splice(Math.floor(Math.random()*dunesfolkMaleB.length),1);
            var getMaleC = dunesfolkMaleC.splice(Math.floor(Math.random()*dunesfolkMaleC.length),1);
            var getMaleCTwo = getMaleC.toLocaleString().toLowerCase().split(',');
            document.querySelector('.name').innerHTML= getMaleA + getMaleATwo + getMaleB + ' ' + getMaleC + getMaleCTwo + getMaleB;
        }
    } else if (raceOption === 'dunesfolk' && genderOption === 'female'){
        for (let i = 0; i <= 1; i++){
            var dunesfolkA = ["Zo", "Mo", "Ko", "Yor", "Wa", "Wo", "Al", "Wi", "No", "Bo", "Ba", "Ra", "Ma", "Re", "Ro", "Ru", "Pi", "Po", "Pu", "Ji", "Jo", "Ja", "Ju", "Ki", "Ka", "Ku", "Li", "La", "Le", "Vi", "Ve", "Va"];
            var dunesfolkFemaleB = ["ri", "gu", "ga", "ya", "da", "ra", "ta", "tu", "ti", "pa", "po", "pi", "ma", "mi", "mo", "yo", "yi", "yobi", "ya", "mu", "na", "nu", "no", "to", "ta", "te", "la", "lo", "li", "wa", "ba", "bi", "bo", "bu", "zi", "za", "zo", "hi", "ha", "ho", "hu"];
            var getFemaleA = dunesfolkA.splice(Math.floor(Math.random()*dunesfolkA.length),1);
            var getFemaleATwo = getFemaleA.toLocaleString().toLowerCase().split(',');
            var getFemaleB = dunesfolkFemaleB.splice(Math.floor(Math.random()*dunesfolkFemaleB.length),1);
            document.querySelector('.name').innerHTML= getFemaleA + getFemaleATwo + getFemaleB + ' ' + getFemaleA + getFemaleB;
        }
    
    // Sea Wolf Roegadyn
    } else if (raceOption === 'sea-wolf' && genderOption === 'male'){
        var seawolfNames = ["Abar", "Abyl", "Aent", "Aerg", "Aerm", "Aerst", "Agat", "Agynn", "Ahl", "Ahld", "Ahr", "Ahrm", "Aht", "Ahtza", "Alyr", "Ask", "Ais", "Anka", "Ansa", "Aren", "Awyr", "Baen", "Bhir", "Bhrat", "Blan", "Blaet", "Bloe", "Blyss", "Blyn", "Bluom", "Brem", "Braen", "Bran", "Born", "Broes", "Boes", "Brot", "Bryda", "Byrg", "Byrgin", "Byrm", "Bylg", "Byrt", "Caepf", "Caer", "Ceig", "Cwaen", "Cwin", "Dani", "Daeg", "Denkyr", "Dehm", "Doen", "Does", "Dornn", "Dorpf", "Draeg", "Draga", "Drys", "Dyn", "Dyrf", "Dyrst", "Eidin", "Eifa", "Elak", "Elil", "Ent", "Erna", "Ewan", "Eyha", "Eyhil", "Eyn", "Eyri", "Edz", "Eynli", "Faeld", "Falk", "Farr", "Fatyr", "Fhil", "Fhis", "Fian", "Firk", "Flaz", "Flekk", "Floeg", "Floer", "Floh", "Foer", "Foet", "Fohc", "Folg", "Froe", "Froa", "Frusk", "Frut", "Fryd", "Fryn", "Fyr", "Fyst", "Gaez", "Ganz", "Gara", "Geim", "Germa", "Ghim", "Glac", "Glaz", "Goht", "Ghota", "Graeb", "Grein", "Grina", "Grym", "Gryne", "Hald", "Harr", "Hart", "Himal", "Hint", "Hirks", "Hyrks", "Holas", "Holl", "Horsk", "Horsam", "Hort", "Isil", "Keten", "Khan", "Khezl", "Kirz", "Klyng", "Knod", "Koen", "Krepf", "Koena", "Laent", "Lago", "Lamm", "Lahz", "Leita", "Liht", "Loet", "Loef", "Lorh", "Lora", "Lydir", "Lubd", "Loug", "Mhol", "Merl", "Marm", "Mhud", "Moeg", "Moen", "Moer", "Mynd", "Myte", "Nahct", "Nebb", "Nedyr", "Noez", "Nort", "Nortyr", "Nyst", "Oebb", "Oefyr", "Oeya", "Ofan", "Opyl", "Orn", "Ost", "Oyura", "Orr", "Pfar", "Pfrew", "Pfef", "Pfyn", "Phati", "Rael", "Raen", "Raeng", "Raet", "Ramm", "Rhen", "Rheti", "Rhit", "Rhyl", "Roegon", "Roega", "Roeh", "Ronth", "Ronn", "Rostn", "Ruht", "Ryhmm", "Ryss", "Saelb", "Saelz", "Saem", "Saes", "Skal", "Skapf", "Skrat", "Skoen", "Skarn", "Skal", "Skart", "Skeit", "Spart", "Solk", "Spaer", "Some", "Soemir", "Smyd", "Spyr", "Sthal", "Sthan", "Stral", "Stymm", "Styrn", "Swys", "Swysta", "Swar", "Sweig", "Syk", "Sylb", "Syng", "Syngi", "Syz", "Syzn", "Thor", "Thosin", "Thota", "Thuba", "Thubyr", "Toega", "Trahg", "Trachyn", "Toum", "Todd", "Thuv", "Ulm", "Ubyl", "Und", "Urs", "Usyn", "Unta", "Und", "Ubyl", "Waeb", "Waek", "Waem", "Waht", "Wakk", "Wall", "Wann", "Weitz", "Whad", "Wezzn", "Weitz", "Wist", "Wistyr", "Wunt", "Woll", "Wolk", "Woerd", "Wilf", "Wurt", "Wyb", "Wyrka", "Wyrk", "Wyda", "Wyrst", "Wyss", "Wyta", "Wyzn", "Ybolg", "Zaen", "Zaes", "Zagyl", "Zahr", "Zant", "Zedyr", "Zent", "Zirn", "Zoenig", "Zoer", "Zwelf", "Zwyn"];
        var getName = Math.floor(Math.random() * seawolfNames.length);
        var lowerCase = Math.floor(Math.random() * seawolfNames.length);
        var getLowerCase = seawolfNames[lowerCase].toLocaleString().toLowerCase();
        var lowerCase2 = Math.floor(Math.random() * seawolfNames.length);
        var getSurname1 = Math.floor(Math.random() * seawolfNames.length);
        var getSurname2 = seawolfNames[lowerCase2].toLocaleString().toLowerCase();
        var getSurname3 = seawolfMaleSurname;
        
        document.querySelector('.name').innerHTML= seawolfNames[getName] + getLowerCase + ' ' + seawolfNames[getSurname1] + getSurname2 + getSurname3;
    } else if (raceOption === 'sea-wolf' && genderOption === 'female'){
        var seawolfNames = ["Abar", "Abyl", "Aent", "Aerg", "Aerm", "Aerst", "Agat", "Agynn", "Ahl", "Ahld", "Ahr", "Ahrm", "Aht", "Ahtza", "Alyr", "Ask", "Ais", "Anka", "Ansa", "Aren", "Awyr", "Baen", "Bhir", "Bhrat", "Blan", "Blaet", "Bloe", "Blyss", "Blyn", "Bluom", "Brem", "Braen", "Bran", "Born", "Broes", "Boes", "Brot", "Bryda", "Byrg", "Byrgin", "Byrm", "Bylg", "Byrt", "Caepf", "Caer", "Ceig", "Cwaen", "Cwin", "Dani", "Daeg", "Denkyr", "Dehm", "Doen", "Does", "Dornn", "Dorpf", "Draeg", "Draga", "Drys", "Dyn", "Dyrf", "Dyrst", "Eidin", "Eifa", "Elak", "Elil", "Ent", "Erna", "Ewan", "Eyha", "Eyhil", "Eyn", "Eyri", "Edz", "Eynli", "Faeld", "Falk", "Farr", "Fatyr", "Fhil", "Fhis", "Fian", "Firk", "Flaz", "Flekk", "Floeg", "Floer", "Floh", "Foer", "Foet", "Fohc", "Folg", "Froe", "Froa", "Frusk", "Frut", "Fryd", "Fryn", "Fyr", "Fyst", "Gaez", "Ganz", "Gara", "Geim", "Germa", "Ghim", "Glac", "Glaz", "Goht", "Ghota", "Graeb", "Grein", "Grina", "Grym", "Gryne", "Hald", "Harr", "Hart", "Himal", "Hint", "Hirks", "Hyrks", "Holas", "Holl", "Horsk", "Horsam", "Hort", "Isil", "Keten", "Khan", "Khezl", "Kirz", "Klyng", "Knod", "Koen", "Krepf", "Koena", "Laent", "Lago", "Lamm", "Lahz", "Leita", "Liht", "Loet", "Loef", "Lorh", "Lora", "Lydir", "Lubd", "Loug", "Mhol", "Merl", "Marm", "Mhud", "Moeg", "Moen", "Moer", "Mynd", "Myte", "Nahct", "Nebb", "Nedyr", "Noez", "Nort", "Nortyr", "Nyst", "Oebb", "Oefyr", "Oeya", "Ofan", "Opyl", "Orn", "Ost", "Oyura", "Orr", "Pfar", "Pfrew", "Pfef", "Pfyn", "Phati", "Rael", "Raen", "Raeng", "Raet", "Ramm", "Rhen", "Rheti", "Rhit", "Rhyl", "Roegon", "Roega", "Roeh", "Ronth", "Ronn", "Rostn", "Ruht", "Ryhmm", "Ryss", "Saelb", "Saelz", "Saem", "Saes", "Skal", "Skapf", "Skrat", "Skoen", "Skarn", "Skal", "Skart", "Skeit", "Spart", "Solk", "Spaer", "Some", "Soemir", "Smyd", "Spyr", "Sthal", "Sthan", "Stral", "Stymm", "Styrn", "Swys", "Swysta", "Swar", "Sweig", "Syk", "Sylb", "Syng", "Syngi", "Syz", "Syzn", "Thor", "Thosin", "Thota", "Thuba", "Thubyr", "Toega", "Trahg", "Trachyn", "Toum", "Todd", "Thuv", "Ulm", "Ubyl", "Und", "Urs", "Usyn", "Unta", "Und", "Ubyl", "Waeb", "Waek", "Waem", "Waht", "Wakk", "Wall", "Wann", "Weitz", "Whad", "Wezzn", "Weitz", "Wist", "Wistyr", "Wunt", "Woll", "Wolk", "Woerd", "Wilf", "Wurt", "Wyb", "Wyrka", "Wyrk", "Wyda", "Wyrst", "Wyss", "Wyta", "Wyzn", "Ybolg", "Zaen", "Zaes", "Zagyl", "Zahr", "Zant", "Zedyr", "Zent", "Zirn", "Zoenig", "Zoer", "Zwelf", "Zwyn"];
        var getName = Math.floor(Math.random() * seawolfNames.length);
        var lowerCase = Math.floor(Math.random() * seawolfNames.length);
        var getFemaleSuffix = Math.floor(Math.random() * seawolfFemaleSuffix.length);
        var lowerCase2 = Math.floor(Math.random() * seawolfNames.length);
        var getSurname1 = Math.floor(Math.random() * seawolfNames.length);
        var getSurname2 = seawolfNames[lowerCase2].toLocaleString().toLowerCase();
        var getSurname3 = seawolfFemaleSurname;
        
        document.querySelector('.name').innerHTML= seawolfNames[getName] + seawolfFemaleSuffix[getFemaleSuffix] + ' ' + seawolfNames[getSurname1] + getSurname2 + getSurname3;

    // Hellsguard Roegadyn
    } else if (raceOption === 'hellsguard' && genderOption === 'male'){
        document.querySelector('.name').innerHTML= hellsguardMaleNames[randomHellsguardMaleFirstName] + " " + hellsguardMaleSurnames[randomHellsguardMaleSurname];
    } else if (raceOption === 'hellsguard' && genderOption === 'female'){
        document.querySelector('.name').innerHTML= hellsguardFemaleNames[randomHellsguardFemaleFirstName] + " " + hellsguardFemaleSurnames[randomHellsguardFemaleSurname];

    // Duskwight & Wildwood Elezen 
    } else if (raceOption === 'duskwight'  && genderOption === 'male') {
        document.querySelector('.name').innerHTML= elezenMaleNames[randomElezenMaleName] + " " + elezenSurnames[randomElezenSurname];
    } else if (raceOption === 'duskwight' && genderOption === 'female'){
        document.querySelector('.name').innerHTML= elezenFemaleNames[randomElezenFemaleName] + " " + elezenSurnames[randomElezenSurname]; 
    } else if (raceOption === 'wildwood' && genderOption === 'female'){
        document.querySelector('.name').innerHTML= elezenFemaleNames[randomElezenFemaleName] + " " + elezenSurnames[randomElezenSurname]; 
    } else if (raceOption === 'wildwood'  && genderOption === 'male') {
        document.querySelector('.name').innerHTML= elezenMaleNames[randomElezenMaleName] + " " + elezenSurnames[randomElezenSurname];

    // Raen Au Ra
    } else if (raceOption === 'raen'  && genderOption === 'male'){
        document.querySelector('.name').innerHTML= raenMaleFirstNames[randomRaenMaleName] + ' ' + raenSurnames[randomRaenSurnames];
    } else if (raceOption === 'raen'  && genderOption === 'female'){
        document.querySelector('.name').innerHTML= raenFemaleNames[randomRaenFemaleName] + ' ' + raenSurnames[randomRaenSurnames];

    // Xaela Au Ra
    } else if (raceOption === 'xaela'  && genderOption === 'male'){
        document.querySelector('.name').innerHTML= xaelaMaleNames[randomXaelaMaleName] + ' ' + xaelaSurnames[randomXaelaSurname];
    } else if (raceOption === 'xaela'  && genderOption === 'female'){
        document.querySelector('.name').innerHTML= xaelaFemaleNames[randomXaelaFemaleName] + ' ' + xaelaSurnames[randomXaelaSurname];
    }      


})

